[package]
name = "big-tr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bdk = {version = "0.23.0", features = ["rpc"]}
bitcoin = "0.28.1"
bitcoincore-rpc = "0.15.0"
